# Runs the model file reader over every instance in the manifest and writes
# bench/parse-report.md.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-parse.ps1
#
# The report records the toolchain version and the commit it was produced from,
# so a number in it can always be traced back to the code that produced it.

param(
  [string]$Manifest = (Join-Path $PSScriptRoot "data/instances/manifest.txt"),
  [string]$Output = (Join-Path $PSScriptRoot "parse-report.md"),
  [string]$Moon = "moon"
)

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $PSScriptRoot

if (-not (Test-Path $Manifest)) {
  Write-Error "manifest not found: $Manifest (run bench/fetch-instances.ps1 first)"
  exit 2
}

Push-Location $root
try {
  $version = (& $Moon version --all 2>&1 | Out-String).Trim()
  $commit = (& git rev-parse --short HEAD 2>&1 | Out-String).Trim()
  $lines = & $Moon run cmd/parse -- --manifest $Manifest 2>&1 | ForEach-Object { $_.ToString() }
} finally {
  Pop-Location
}

$rows = @()
$failures = @()
$currentFailure = $null
foreach ($line in $lines) {
  if ($line -match '^OK\s+(\S+)\s+format=(\S+)\s+vars=(\d+)\s+cons=(\d+)\s+nnz=(\d+)\s+int=(\d+)\s+sense=(\S+)\s+(\S+)') {
    $rows += [pscustomobject]@{
      Instance = Split-Path -Leaf $Matches[1]
      Vars     = [int]$Matches[3]
      Cons     = [int]$Matches[4]
      Nonzeros = [int]$Matches[5]
      Integers = [int]$Matches[6]
      Sense    = $Matches[7]
      Verdict  = $Matches[8]
    }
    continue
  }
  if ($line -match '^FAIL\s+(\S+)') {
    $currentFailure = [pscustomobject]@{ Instance = Split-Path -Leaf $Matches[1]; Reason = "" }
    $failures += $currentFailure
    continue
  }
  if ($null -ne $currentFailure -and $line.Trim() -ne "") {
    $currentFailure.Reason = $line.Trim()
    $currentFailure = $null
  }
}

$total = $rows.Count + $failures.Count
$build = @()
$build += "# Model file parse report"
$build += ""
$build += "Generated by ``bench/report-parse.ps1`` from commit ``$commit``."
$build += ""
$build += "- Toolchain: ``$($version -replace "`r?`n", " | ")``"
$build += "- Instances: MIPLIB 2017 (<https://miplib.zib.de>), downloaded by ``bench/fetch-instances.ps1``;"
$build += "  the files themselves are not redistributed by this repository (see ``bench/README.md``)."
$build += "- Reader: ``Freon793/moonopt/format`` (MPS), driven through ``moon run cmd/parse``."
$build += ""
$build += "## Summary"
$build += ""
$build += "| metric | value |"
$build += "| --- | --- |"
$build += "| instances attempted | $total |"
$build += "| parsed | $($rows.Count) |"
$build += "| failed | $($failures.Count) |"
if ($rows.Count -gt 0) {
  $build += "| largest model (nonzeros) | $(($rows | Sort-Object Nonzeros -Descending | Select-Object -First 1).Instance) - $(($rows | Measure-Object Nonzeros -Maximum).Maximum) nonzeros |"
  $build += "| total variables | $(($rows | Measure-Object Vars -Sum).Sum) |"
  $build += "| total constraints | $(($rows | Measure-Object Cons -Sum).Sum) |"
  $build += "| total nonzeros | $(($rows | Measure-Object Nonzeros -Sum).Sum) |"
  $build += "| models with integer columns | $(($rows | Where-Object { $_.Integers -gt 0 }).Count) |"
  $build += "| models with validation warnings | $(($rows | Where-Object { $_.Verdict -ne 'ok' }).Count) |"
}
$build += ""
$build += "## Parsed instances (largest first)"
$build += ""
$build += "| instance | vars | cons | nonzeros | integer vars | sense | validation |"
$build += "| --- | ---: | ---: | ---: | ---: | --- | --- |"
foreach ($row in ($rows | Sort-Object Nonzeros -Descending)) {
  $build += "| $($row.Instance) | $($row.Vars) | $($row.Cons) | $($row.Nonzeros) | $($row.Integers) | $($row.Sense) | $($row.Verdict) |"
}
$build += ""
$build += "## Failures"
$build += ""
if ($failures.Count -eq 0) {
  $build += "None."
} else {
  foreach ($failure in $failures) {
    $build += "- ``$($failure.Instance)`` - $($failure.Reason)"
  }
}
$build += ""
[IO.File]::WriteAllLines($Output, $build)
Write-Host ("wrote {0}: {1} parsed, {2} failed" -f $Output, $rows.Count, $failures.Count)
if ($failures.Count -gt 0) {
  $failures | ForEach-Object { Write-Host ("  FAIL {0}: {1}" -f $_.Instance, $_.Reason) }
}
