# Runs the kernel over the instances in the manifest and writes
# bench/solve-report.md.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-solve.ps1
#
# Instances whose row count exceeds -MaxRows are reported as skipped rather than
# attempted: the kernel keeps a dense basis inverse, so a large model needs the
# sparse factorization that is the next milestone, and a ten minute hang would
# look like a defect instead of a boundary.
#
# The report records the toolchain version and the commit it came from, so every
# number in it can be traced back to the code that produced it.

param(
  [string]$Manifest = (Join-Path $PSScriptRoot "data/instances/manifest.txt"),
  [string]$Output = (Join-Path $PSScriptRoot "solve-report.md"),
  [int]$MaxRows = 200,
  [switch]$Relax,
  [string]$Moon = "moon"
)

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $PSScriptRoot

if (-not (Test-Path $Manifest)) {
  Write-Error "manifest not found: $Manifest (run bench/fetch-instances.ps1 first)"
  exit 2
}

Push-Location $root
try {
  $version = (& $Moon version --all 2>&1 | Out-String).Trim()
  $commit = (& git rev-parse --short HEAD 2>&1 | Out-String).Trim()
  $arguments = @("run", "cmd/parse", "--", "--manifest", $Manifest, "--solve", "--max-rows", "$MaxRows")
  if ($Relax) { $arguments += "--relax" }
  $lines = & $Moon @arguments 2>&1 | ForEach-Object { $_.ToString() }
} finally {
  Pop-Location
}

$rows = @()
$current = $null
foreach ($line in $lines) {
  if ($line -match '^OK\s+(\S+)\s+format=(\S+)\s+vars=(\d+)\s+cons=(\d+)\s+nnz=(\d+)\s+int=(\d+)\s+sense=(\S+)\s+(\S+)') {
    $current = [pscustomobject]@{
      Instance   = Split-Path -Leaf $Matches[1]
      Vars       = [int]$Matches[3]
      Cons       = [int]$Matches[4]
      Nonzeros   = [int]$Matches[5]
      Integers   = [int]$Matches[6]
      Solve      = "-"
      Objective  = ""
      Iterations = ""
      Note       = ""
    }
    $rows += $current
    continue
  }
  if ($null -ne $current -and $line -match '^\s+solve=(\S+)') {
    $current.Solve = $Matches[1]
    if ($line -match 'obj=(\S+)\s+iters=(\d+)') {
      $current.Objective = $Matches[1]
      $current.Iterations = $Matches[2]
    }
    if ($line -match '\((.*)\)\s*$') {
      $current.Note = $Matches[1]
    }
  }
}

$optimal = @($rows | Where-Object { $_.Solve -eq "optimal" })
$skipped = @($rows | Where-Object { $_.Solve -like "skipped*" })
$other = @($rows | Where-Object { $_.Solve -ne "-" -and $_.Solve -ne "optimal" -and $_.Solve -notlike "skipped*" })

$build = @()
$build += "# Kernel solve report"
$build += ""
$build += "Generated by ``bench/report-solve.ps1`` from commit ``$commit``."
$build += ""
$build += "- Toolchain: ``$($version -replace "`r?`n", " | ")``"
$build += "- Instances: MIPLIB 2017 (<https://miplib.zib.de>), fetched by ``bench/fetch-instances.ps1``."
$build += "- Mode: $(if ($Relax) { "LP relaxation (integer columns treated as continuous)" } else { "as-is (integer models are refused by the linear kernel)" }), row limit $MaxRows."
$build += ""
$build += "## Summary"
$build += ""
$build += "| metric | value |"
$build += "| --- | --- |"
$build += "| instances in manifest | $($rows.Count) |"
$build += "| solved to optimality | $($optimal.Count) |"
$build += "| skipped (row count over the limit) | $($skipped.Count) |"
$build += "| other outcomes | $($other.Count) |"
if ($optimal.Count -gt 0) {
  $build += "| pivot iterations (total) | $(($optimal | Measure-Object Iterations -Sum).Sum) |"
  $build += "| largest solved model (rows) | $(($optimal | Sort-Object Cons -Descending | Select-Object -First 1).Cons) |"
}
$build += ""
if ($other.Count -gt 0) {
  $build += "Outcomes other than optimal are listed verbatim below; a numerical failure is a"
  $build += "measured verdict from the kernel's own residual check, not a silent wrong answer."
  $build += ""
}
$build += "## Instances"
$build += ""
$build += "| instance | vars | cons | nonzeros | integer vars | solve | objective | pivots | note |"
$build += "| --- | ---: | ---: | ---: | ---: | --- | ---: | ---: | --- |"
foreach ($row in $rows) {
  $build += "| $($row.Instance) | $($row.Vars) | $($row.Cons) | $($row.Nonzeros) | $($row.Integers) | $($row.Solve) | $($row.Objective) | $($row.Iterations) | $($row.Note) |"
}
$build += ""
[IO.File]::WriteAllLines($Output, $build)
Write-Host ("wrote {0}: optimal={1} skipped={2} other={3}" -f $Output, $optimal.Count, $skipped.Count, $other.Count)
foreach ($row in $other) {
  Write-Host ("  {0}: {1} {2}" -f $row.Instance, $row.Solve, $row.Note)
}
