# Builds bench/report.md: the index of every report this repository publishes, the exact
# command that regenerates each one, and whether the code behind it has changed since.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File bench/report.ps1
#
# A report is evidence only while the code it describes is still the code in the tree, and
# nothing else in the repository answers "which of these reports are current". This script
# answers it mechanically: it reads the commit each report recorded for itself, diffs the
# source paths that report depends on between that commit and HEAD, and marks the report
# STALE when any of them changed.
#
# Stale is not a failure - a report a later change invalidated is still the record of the
# run that happened - but it is not evidence for the current code either, so the index says
# which it is instead of leaving a reader to find out.
#
# The script refuses to write an index it cannot stand behind:
#   - a listed report file is missing;
#   - a report's recorded commit or one of its summary numbers cannot be read, because an
#     index that prints a guessed number is worse than no index at all;
#   - git cannot answer the staleness question (no repository, no history).
#
# Adding a report to the project means adding one entry to $reports and nothing else.

param(
  [string]$Output = (Join-Path $PSScriptRoot "report.md"),
  [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Continue"

# The reports, in the order a reader should read them: input first, then the kernel, then
# branch and bound at each of its two budgets. `Paths` is what each report's numbers depend
# on - a change anywhere in there makes the report a statement about older code.
$reports = @(
  @{
    File = "bench/parse-report.md"
    Scope = "model file parsing (MPS/LP reader)"
    Metrics = @("instances attempted", "parsed", "failed")
    Paths = @("format", "model", "cmd/parse")
    Command = "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-parse.ps1"
    Backs = "the claim that the reader takes the whole manifest: every instance parses, none fails"
  },
  @{
    File = "bench/solve-report.md"
    Scope = "continuous kernel (LP relaxation, presolve, certificates)"
    Metrics = @("instances in manifest", "solved to optimality", "skipped (row count over the limit)", "other outcomes")
    Paths = @("simplex", "presolve", "verify", "core", "model", "cmd/parse")
    Command = "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-solve.ps1 -Relax -MaxRows 1000 -MaxIterations 1200 -Presolve"
    Backs = "the kernel's answer quality on real models: optima found, size refusals, numerical failures"
  },
  @{
    File = "bench/mip-report.md"
    Scope = "branch and bound, 300-node budget over the whole manifest"
    Metrics = @("instances in manifest", "proven optimal (tree exhausted or every open bound closed)", "stopped at the node budget", "skipped (row count over the limit)", 'relaxations verified by `verify`', 'cuts added and verified by `verify_cut`')
    Paths = @("mip", "simplex", "verify", "presolve", "core", "model", "cmd/parse")
    Command = "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-mip.ps1 -MaxRows 300 -MaxNodes 300 -MaxIterations 5000"
    Backs = "that no run ends on a refused certificate, and that every reported point is an integer point of the model"
  },
  @{
    File = "bench/mip-report-small.md"
    Scope = "branch and bound, 20000-node budget over the small-instance list"
    Metrics = @("instances in manifest", "proven optimal (tree exhausted or every open bound closed)", "stopped at the node budget", 'relaxations verified by `verify`', 'cuts added and verified by `verify_cut`')
    Paths = @("mip", "simplex", "verify", "presolve", "core", "model", "cmd/parse")
    Command = "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-mip.ps1 -Manifest bench/data/instances/small.txt -MaxRows 300 -MaxNodes 20000 -MaxIterations 20000 -Output bench/mip-report-small.md"
    Backs = "the M5 criterion that small integer instances reach their published optimum; cross-checked by bench/check-mip-objectives.ps1, which compares each proven objective with MIPLIB's own table and requires equality"
  }
)

function Get-ReportCommit([string[]]$lines) {
  foreach ($line in $lines) {
    if ($line -match 'Generated by `[^`]+` from commit `([0-9a-f]+)`') {
      return $Matches[1]
    }
  }
  return ""
}

function Get-ReportMetric([string[]]$lines, [string]$name) {
  $pattern = '^\|\s*' + [regex]::Escape($name) + '\s*\|\s*([^|]+?)\s*\|'
  foreach ($line in $lines) {
    if ($line -match $pattern) {
      return $Matches[1]
    }
  }
  return ""
}

Push-Location $Root
try {
  $head = (& git rev-parse --short HEAD 2>&1 | Out-String).Trim()
  if ($LASTEXITCODE -ne 0 -or $head -notmatch '^[0-9a-f]+$') {
    Write-Error "cannot read HEAD from git; no report written"
    exit 4
  }
  $headDate = (& git log -1 --format=%cs 2>&1 | Out-String).Trim()
  $toolchain = ""
  $rows = @()
  $stale = @()
  foreach ($report in $reports) {
    if (-not (Test-Path $report.File)) {
      Write-Error ("report not found: {0}" -f $report.File)
      exit 2
    }
    $lines = [IO.File]::ReadAllLines((Join-Path $Root $report.File))
    $commit = Get-ReportCommit $lines
    if ($commit -eq "") {
      Write-Error ("no recorded commit in {0}; the index would not know what the numbers describe" -f $report.File)
      exit 3
    }
    # The toolchain is recorded per report; the first report's line is the one the index
    # prints, and a mismatch between reports is worth saying out loud rather than hiding.
    $line = ($lines | Where-Object { $_ -match '^- Toolchain:' } | Select-Object -First 1)
    if ($null -ne $line) {
      # The line is copied verbatim from the report it came from, minus the list marker: the
      # index writes its own, so keeping this one would print it twice.
      $line = ($line -replace '^- ', '')
      if ($toolchain -eq "") {
        $toolchain = $line
      } elseif ($line -ne $toolchain) {
        $toolchain = $toolchain + " (reports disagree)"
      }
    }
    $result = @()
    foreach ($name in $report.Metrics) {
      $value = Get-ReportMetric $lines $name
      if ($value -eq "") {
        Write-Error ("{0} has no '{1}' row in its summary; the index cannot read it" -f $report.File, $name)
        exit 3
      }
      $result += ("{0}: {1}" -f ($name -replace ' \(.*\)$', ''), $value)
    }
    $changed = @(& git diff --name-only ("{0}..HEAD" -f $commit) -- $report.Paths 2>&1 | Where-Object { $_ -ne "" })
    if ($LASTEXITCODE -ne 0) {
      Write-Error ("git cannot compare {0} with HEAD; no report written" -f $commit)
      exit 4
    }
    $status = "current"
    if ($changed.Count -gt 0) {
      $status = ("STALE ({0} changed since)" -f $changed.Count)
      $sample = @($changed | Select-Object -First 3) -join ", "
      $stale += ("{0}: generated at {1}, {2} file(s) under its own paths changed since - {3}" -f $report.File, $commit, $changed.Count, $sample)
    }
    $rows += @{
      Report = $report
      Commit = $commit
      Result = ($result -join ", ")
      Status = $status
    }
  }
} finally {
  Pop-Location
}

$build = @()
$build += "# Benchmark reports"
$build += ""
$build += "Generated by ``bench/report.ps1`` from commit ``$head`` ($headDate)."
$build += ""
$build += "- $toolchain"
$build += "- Instances: MIPLIB 2017 (<https://miplib.zib.de>), fetched by ``bench/fetch-instances.ps1``;"
$build += "  the data itself is not redistributed (see ``bench/README.md``)."
$build += "- Every report below is written by its own script, and every one of those scripts refuses to"
$build += "  write unless its run finished, covered every manifest entry, and passed its own checks:"
$build += "  no certificate refused, every reported point an integer point of the model. This file is"
$build += "  the index of them, and it is the only place that says which of them the current code"
$build += "  still backs."
$build += ""
$build += "## Reports"
$build += ""
$build += "| report | scope | result | generated at | code behind it |"
$build += "| --- | --- | --- | --- | --- |"
foreach ($row in $rows) {
  $name = Split-Path -Leaf $row.Report.File
  $build += ("| [{0}]({1}) | {2} | {3} | ``{4}`` | {5} |" -f $name, $name, $row.Report.Scope, $row.Result, $row.Commit, $row.Status)
}
$build += ""
$build += "``current`` means no file under the report's own source paths changed between the commit it"
$build += "was generated from and HEAD, so the numbers still describe the code in the tree. ``STALE``"
$build += "means they describe an older one: the run happened and the report is its record, but"
$build += "re-running the command would not have to reproduce it. Regenerating a stale report is part"
$build += "of the round that made it stale, and this table is how that is noticed."
$build += ""
$build += "The staleness test is deliberately conservative: it compares the *files* a report's numbers"
$build += "depend on, so a changed comment counts as a change even though it cannot move a number."
$build += "That direction is the safe one - a report is flagged when it might no longer describe the"
$build += "current code, never cleared when it might not - and the only thing that settles a flagged"
$build += "report is re-running its command (or measuring that the numbers it would print are"
$build += "unchanged, which is worth writing down where it was measured)."
$build += ""
$build += "## What each report is evidence for"
$build += ""
foreach ($row in $rows) {
  $name = Split-Path -Leaf $row.Report.File
  $build += ("- ``{0}``: {1}" -f $name, $row.Report.Backs)
}
$build += ""
$build += "## How to reproduce"
$build += ""
$build += "Run these in order in the repository root. The first one downloads the instances and"
$build += "writes ``bench/data/instances/manifest.txt``; the rest read them and take minutes to hours,"
$build += "because they solve the whole manifest."
$build += ""
$build += "``````powershell"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/fetch-instances.ps1"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-parse.ps1"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-solve.ps1 -Relax -MaxRows 1000 -MaxIterations 1200 -Presolve"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/check-relaxation-bounds.ps1"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-mip.ps1 -MaxRows 300 -MaxNodes 300 -MaxIterations 5000"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report-mip.ps1 -Manifest bench/data/instances/small.txt -MaxRows 300 -MaxNodes 20000 -MaxIterations 20000 -Output bench/mip-report-small.md"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/check-mip-objectives.ps1"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/check-mip-objectives.ps1 -Report bench/mip-report-small.md"
$build += "powershell -NoProfile -ExecutionPolicy Bypass -File bench/report.ps1"
$build += "``````"
$build += ""
if ($stale.Count -gt 0) {
  $build += "## Reports flagged stale"
  $build += ""
  foreach ($line in $stale) {
    $build += ("- {0}" -f $line)
  }
  $build += ""
}

[IO.File]::WriteAllLines($Output, $build)
Write-Host ("wrote {0}: {1} report(s), {2} stale" -f $Output, $rows.Count, $stale.Count)
foreach ($line in $stale) {
  Write-Host ("  {0}" -f $line)
}
